db.questions.save({"category":"Words","question":"Furfur","answer":"Flakes of Dandruff"});
db.questions.save({"category":"Words","question":"Flews","answer":"The upper lip flaps on certain dogs"});
db.questions.save({"category":"Words","question":"Boontling","answer":"A kind of double talk which originated in Boonville California"});
db.questions.save({"category":"Words","question":"Zobo","answer":"What you get when you mate a zebra with a yak"});
db.questions.save({"category":"Words","question":"Sesquipedalian","answer":"Pertaining to excessively long words"});
db.questions.save({"category":"People","question":"Chandra Barman","answer":"He is the tallest living person, standing 8'3\""});
db.questions.save({"category":"People","question":"Joe Sobek","answer":"Professional tennis and squash player who invented the game of tennis"});
db.questions.save({"category":"People","question":"Harvey Wilcox","answer":"Real estate mogul who was the original owner of Hollywood, California"});
db.questions.save({"category":"People","question":"Tawarik Makutin","answer":"Arabian math whiz who invented the zero symbol"});
db.questions.save({"category":"People","question":"Karl Pabst","answer":"Inventor of the jeep"});
db.questions.save({"category":"Initials","question":"N.E.A.A.","answer":"Norwegian Elkhound Association of America"});
db.questions.save({"category":"Initials","question":"P.M.A.","answer":"Peat Moss Association"});
db.questions.save({"category":"Initials","question":"R.H.S.","answer":"Rodeo Historical Society"});
db.questions.save({"category":"Initials","question":"W.A.G.","answer":"Wine Appreciation Guild"});
db.questions.save({"category":"Initials","question":"N.A.A.M.","answer":"National Association of Anvil Makers"});
db.questions.save({"category":"Movies","question":"The Secret of the Blue Moon","answer":"Three men, all in love with the same woman, agree to spend the night in a haunted room of her mansion"});
db.questions.save({"category":"Movies","question":"Hold On!","answer":"1966 musical featuring the sixties group Herman's Hermits, who try to get their name on the side of a spaceship"});
db.questions.save({"category":"Movies","question":"Dirty Laundry","answer":"A bumbling schnook gets screwed up with gangsters when his laundry is mixed up with a million bucks in drug money"});
db.questions.save({"category":"Movies","question":"Talking Walls","answer":"A college student listens through motel walls so he can finish his thesis on human behavior"});
db.questions.save({"category":"Movies","question":"Three Nuts in Search of a Bolt","answer":"Three loonis save money by hiring an actor to act out their personalities with a psychiatrist"});
db.questions.save({"category":"Dates","question":"March 13, 1961","answer":"Pablo Picasso married his model"});
db.questions.save({"category":"Dates","question":"September 18, 1964","answer":"The first episode of the Addams Family went on TV"});
db.questions.save({"category":"Dates","question":"December 7, 1945","answer":"The first Baskin & Robbins ice cream store opened"});
db.questions.save({"category":"Dates","question":"November 10, 1989","answer":"The prime minister of Bulgaria resigned"});
db.questions.save({"category":"Dates","question":"August 26, 1920","answer":"American women were given the right to vote"});